name: Playbook
repository: https://github.com/playbook-ui/playbook-flutter

packages:
  - playbook*/**
  - examples/**

ide:
  intellij: true
  vscode: false

command:
  version:
    linkToCommits: true

scripts:
  format: melos exec -- exec flutter format . -l 100

  analyze: melos exec -- exec flutter analyze .

  clean: melos exec -- exec flutter clean

  pub:upgrade:
    run: |
      melos exec -- exec flutter pub upgrade
      melos bootstrap

  gen:build_runner:
    run: |
      melos exec -- exec flutter pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: 'build_runner'

  test:unit:
    run: |
      melos exec -- exec flutter test
    select-package:
      no-depends-on:
        - 'playbook_snapshot'
      dir-exists:
        - test

  test:snapshot:
    run: |
      melos exec -- exec flutter test --update-goldens
    select-package:
      depends-on:
        - 'playbook_snapshot'
      dir-exists:
        - test

  test:snapshot:simple:
    run: |
      melos exec -- exec flutter test --update-goldens
    select-package:
      scope: 'simple_catalog_app'
