name: playbook_ui
description: Playbook UI package.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependency
  playbook:

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
  uses-material-design: true

dependency_overrides:
  playbook:
    path: ../playbook
